import {test} from 'node:test';
import assert from 'node:assert/strict';
import {parseLine,parseText,validDate,validate,speed,summary,improvement,warnings,csv,validateBackup,stableStringify,backupContent,contentHash,splitUtf8Chunks,retryDelay,classifyBackupError,LOCAL_OWNER} from '../core.js';
const now='2026-09-13';
for(const [input,seconds] of [['30公尺 7.42秒',7.42],['30m 7.42s',7.42],['今天30公尺跑7秒42',7.42],['30米 7.42秒',7.42],['30 M 8秒5',8.5],['30公尺 8秒05',8.05],['30公尺 7秒420',7.42],['小孩今天30米跑7秒42',7.42],['30公尺跑了7.42秒',7.42],['３０ｍ ７．４２ｓ',7.42]])test(input,()=>{const r=parseLine(input,now);assert.equal(r.distance,30);assert.equal(r.seconds,seconds);assert.equal(r.date,now);});
for(const input of ['9/13 30米 7秒42','2026/9/13 30m 7.42秒','9-13 30m 7.42s','2026-09-13 30m 7.42s'])test(input,()=>assert.equal(parseLine(input,now).date,now));
test('批次無單位秒數與錯誤列',()=>{const rows=parseText('9/1 30m 8.12\n9/3 30m 7.95\n9/6 30m 7.72\n\n無法辨识',now);assert.equal(rows.length,4);assert.deepEqual(rows.slice(0,3).map(x=>x.record.seconds),[8.12,7.95,7.72]);assert.ok(rows[3].error);});
for(const input of ['30m 0秒','0m 7秒','-30m 7秒','30m -7秒','2026-09-13 30m -7秒','2/30 30m 7秒','30m 7秒 30m 8秒','30m 7.4秒2','30m','2026-13-01 30m 7秒'])test('拒絕 '+input,()=>assert.throws(()=>parseLine(input,now)));
test('日期與數值驗證',()=>{assert.ok(validDate('2024-02-29'));assert.ok(!validDate('2026-02-29'));for(const seconds of [NaN,Infinity,-1,0,'7'])assert.throws(()=>validate({date:now,distance:30,seconds,note:''}));});
const run=(seconds,date='2026-09-13',id='a',extra={})=>({id,childId:'child_01',date,distance:30,seconds,note:'',startType:'',surface:'',timingMethod:'',createdAt:date+'T12:00:00Z',updatedAt:date+'T12:00:00Z',...extra});
test('速度使用未捨入值',()=>{assert.equal(speed(run(7.42)).ms.toFixed(2),'4.04');assert.equal(speed(run(7.42)).kmh.toFixed(2),'14.56');assert.equal(improvement(8.12,7.42).percent.toFixed(1),'8.6');});
test('同距離同小孩，補登按日期排序',()=>{const s=summary([run(7.42),run(8.12,'2026-09-01','b'),run(1,now,'c',{distance:10}),run(2,now,'d',{childId:'other'})],30);assert.equal(s.first.seconds,8.12);assert.equal(s.best.seconds,7.42);assert.equal(s.latest.seconds,7.42);assert.equal(s.list.length,2);});
test('重複與異常提示，編輯不比較自身',()=>{const r=run(8);assert.equal(warnings(r,[r]).length,0);assert.equal(warnings({...r,id:'b'},[r]).length,1);assert.ok(warnings(run(74.2,now,'d'),[run(7,now,'a'),run(8,now,'b'),run(9,now,'c')]).length);});
test('CSV BOM、引號與公式注入防護',()=>{const text=csv([run(7.42,now,'a',{note:'=1+1,"test"\n下一行'})]);assert.ok(text.startsWith('\uFEFF'));assert.ok(text.includes('"\'=1+1,""test""\n下一行"'));});
test('備份格式與關聯驗證',()=>{const data={version:1,children:[{id:'child_01',name:'小孩',birthday:null}],records:[run(7.42)]};assert.equal(validateBackup(data),data);assert.throws(()=>validateBackup({...data,version:2}));assert.throws(()=>validateBackup({...data,records:[run(7),run(8)]}));assert.throws(()=>validateBackup({...data,children:[]}));assert.throws(()=>validateBackup({...data,records:[run(7,now,'a',{timingMethod:'invalid'})]}));});
test('穩定序列化與內容雜湊忽略鍵序',async()=>{
 const a={schemaVersion:1,settings:{reverse:true,theme:'x'},nested:{b:1,a:2}};
 const b={nested:{a:2,b:1},schemaVersion:1,settings:{theme:'x',reverse:true}};
 assert.equal(stableStringify(a),stableStringify(b));
 const rec={id:'r1',childId:'child_01',date:now,distance:30,seconds:7.42,note:'',startType:'',surface:'',timingMethod:'',createdAt:now+'T12:00:00Z',updatedAt:now+'T12:00:00Z',ownerUid:'user-a',updatedNetwork:'nope'};
 const payload=backupContent({children:[{id:'child_01',name:'小孩',birthday:null,ownerUid:'user-a'}],records:[rec],settings:[{id:'lastBackup',value:'t'},{id:'reverse:user-a',value:false}]},'user-a');
 assert.equal(payload.records[0].ownerUid,undefined);
 assert.deepEqual(payload.settings,{reverse:false});
 const hash=await contentHash(payload);
 assert.equal(hash.length,64);
 assert.equal(hash,await contentHash(JSON.parse(JSON.stringify(payload))));
});
test('UTF-8 分塊不切字元且退避有上限',()=>{
 const chunks=splitUtf8Chunks('你好世界',4);
 assert.ok(chunks.every(c=>new TextEncoder().encode(c).length<=4));
 assert.equal(chunks.join(''),'你好世界');
 const delay=retryDelay(10,()=>0.5);
 assert.equal(delay,300000);
 const classified=classifyBackupError({code:'permission-denied',message:'no'});
 assert.equal(classified.fatal,true);
 assert.equal(classifyBackupError({code:'unavailable'}).fatal,false);
 assert.equal(LOCAL_OWNER,'local-only');
});
