import {today,validate,parseText,summary,speed,improvement,chronological,warnings,csv,validateBackup} from './core.js';
import {openDB,all,write} from './db.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={home:'⌂',records:'☷',analysis:'↗',settings:'⚙'};
let records=[],children=[],settings=[],page='home',distance=30,filter='all',preview=[],backup=null,editing=null,busy=false,pasteDraft='';
let draft={date:today(),distance:30,seconds:'',note:'',startType:'',surface:'',timingMethod:''};
const active=()=>children.find(c=>c.id==='child_01')||children[0];
const own=()=>records.filter(r=>r.childId===active().id);
const stat=()=>summary(records,Number(distance),active().id);
const f=n=>Number(n).toFixed(2), short=d=>`${Number(d.slice(5,7))}/${Number(d.slice(8,10))}`;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function delta(before,after){const v=improvement(before,after);return Math.abs(v.seconds)<1e-9?'與前一次相同':`${v.seconds>0?'快':'慢'} ${f(Math.abs(v.seconds))} 秒（${v.seconds>0?'+':'−'}${Math.abs(v.percent).toFixed(1)}%）`;}
function options(values,value){return values.map(([v,t])=>`<option value="${v}" ${v===value?'selected':''}>${t}</option>`).join('');}
function distanceSelect(){return `<label class="filter-label">測試距離<select id="analysis-distance">${[...new Set([10,20,30,40,50,60,100,...own().map(r=>r.distance),Number(distance)])].sort((a,b)=>a-b).map(d=>`<option value="${d}" ${d===Number(distance)?'selected':''}>${d} 公尺</option>`).join('')}</select></label>`;}
function render(){const titles={home:['每一步，都算數。','記下今天的努力，看見明天的進步。'],records:['努力，有跡可循。','每一筆紀錄，都是成長的一小步。'],analysis:['看見自己的進步。','和上一次的自己比，就很好。'],settings:['準備好，再出發。','你的紀錄，由你保管。']};$('#app').innerHTML=`<div class="shell"><header><a class="brand" href="#home"><span class="brandmark">↗</span><span>小步快跑<small>LITTLE STRIDES</small></span></a><span class="profile"><span class="avatar">${esc(active().name.slice(0,1))}</span>${esc(active().name)}</span></header><main><div class="page-heading"><p class="eyebrow">${{home:'READY, SET, GROW',records:'RUNNING JOURNAL',analysis:'YOUR PROGRESS',settings:'MAKE IT YOURS'}[page]}</p><h1>${titles[page][0]}</h1><p>${titles[page][1]}</p></div>${page==='home'?home():page==='records'?recordPage():page==='analysis'?analysis():settingPage()}</main><footer>小小的步伐，也有大大的進步。</footer></div><nav aria-label="主要導覽">${Object.entries({home:'首頁',records:'紀錄',analysis:'分析',settings:'設定'}).map(([key,label])=>`<button data-page="${key}" class="nav-item ${page===key?'active':''}" ${page===key?'aria-current="page"':''}><span aria-hidden="true">${icons[key]}</span>${label}</button>`).join('')}</nav>`;bind();}
function home(){const s=stat();return `<div class="home-grid"><div><section class="card input-card"><div class="section-head"><h2>${editing?'編輯紀錄':'記錄今天的成績'}</h2><span class="pill">${editing?'修改中':'QUICK ADD'}</span></div><form id="run-form"><label class="date-row">測試日期<input aria-label="測試日期" id="date" type="date" required value="${esc(draft.date)}"></label><div class="metric-inputs"><label>距離 <span>公尺</span><input id="distance" type="number" inputmode="decimal" min="0.01" step="any" required value="${esc(draft.distance)}"></label><span class="divider">/</span><label>時間 <span>秒</span><input id="seconds" type="number" inputmode="decimal" min="0.001" step="any" placeholder="7.42" required value="${esc(draft.seconds)}"></label></div><div class="chips" aria-label="距離快捷鍵">${[10,20,30,40,50,60,100].map(d=>`<button type="button" data-distance="${d}" class="chip ${Number(draft.distance)===d?'selected':''}">${d}<small>m</small></button>`).join('')}<button type="button" id="custom" class="chip">自訂</button></div><details ${draft.note||draft.startType||draft.surface||draft.timingMethod?'open':''}><summary>＋ 備註與測試條件 <span>選填</span></summary><label>備註<textarea id="note" placeholder="場地、鞋子、天氣，或今天的小發現…">${esc(draft.note)}</textarea></label><div class="conditions"><label>起跑<select id="startType">${options([['','未指定'],['standing','靜止起跑'],['flying','助跑'],['free','自由跑']],draft.startType)}</select></label><label>場地<select id="surface">${options([['','未指定'],['indoor','室內'],['track','操場'],['asphalt','柏油'],['grass','草地']],draft.surface)}</select></label><label>計時<select id="timingMethod">${options([['','未指定'],['manual','手動'],['video','影片'],['electronic','電子計時']],draft.timingMethod)}</select></label></div></details><button class="primary add" type="submit">${editing?'儲存修改':'＋ 新增紀錄'}<span>↗</span></button>${editing?'<button class="secondary full" type="button" id="cancel-edit">取消編輯</button>':''}<p class="quiet centered">只需輸入秒數，就能記下這一步。</p></form></section><section class="card paste-card"><div class="section-head"><h2><span class="mini-icon">≡</span> 貼上文字，輕鬆記錄</h2><span class="muted">支援多筆</span></div><p class="muted">手邊已經有紀錄？整段貼上就好。</p><textarea id="paste" rows="3" aria-label="貼上跑步紀錄" placeholder="30公尺 7秒42&#10;9/13 30m 7.42秒"></textarea><button class="secondary full" id="parse">自動辨識 <span>→</span></button><div id="preview">${previewHTML()}</div></section></div><aside><section class="card progress-card"><div class="section-head"><h2>最近表現</h2><span class="live-dot">●</span></div>${distanceSelect()}${s?summaryHTML(s):empty('新的起跑線','新增第一筆成績，這裡就會開始記錄進步。')}<button class="text-button" data-page="analysis">查看完整分析 <span>↗</span></button></section><section class="encourage"><div class="track-art" aria-hidden="true"><i></i><i></i><i></i><b>↗</b></div><p>不必跑得比別人快。<br><strong>每次，都更靠近自己。</strong></p></section><p class="storage-note">◉ 資料儲存在這台裝置<br><button class="text-button" data-page="settings">記得定期備份 →</button></p></aside></div>`;}
function summaryHTML(s){const v=s.total;return `<p class="muted">最近一次 · ${short(s.latest.date)}</p><div class="hero-number">${f(s.latest.seconds)}<span>秒</span></div><div class="speed-line">${f(speed(s.latest).ms)} m/s <span>· ${f(speed(s.latest).kmh)} km/h</span></div>${s.latest.seconds===s.best.seconds?'<span class="pb">🏆 目前最佳成績</span>':''}<div class="stat-pair"><div><span>個人最佳</span><strong>${f(s.best.seconds)}<small> 秒</small></strong></div><div><span>第一次</span><strong>${f(s.first.seconds)}<small> 秒</small></strong></div></div>${s.list.length>1?`<div class="improvement ${v.seconds<0?'slower':''}"><span>${v.seconds>=0?'↗':'↘'} 比第一次${v.seconds>=0?'進步':'慢了'}</span><strong>${f(Math.abs(v.seconds))} 秒 <small>（${Math.abs(v.percent).toFixed(1)}%）</small></strong></div><p class="recent-label">近 ${Math.min(3,s.list.length)} 次 <span>${s.list.slice(-3).map(r=>f(r.seconds)).join(' → ')}</span></p><p class="quiet">${s.list.length>=3&&s.list.slice(-3).every((r,i,a)=>i===0||r.seconds<a[i-1].seconds)?'持續進步 ↑':s.previous?`比前一次${delta(s.previous.seconds,s.latest.seconds)}`:''}</p>`:'<p class="quiet">第一筆紀錄，新的起點！</p>'}`;}
function empty(title,text){return `<div class="empty"><span>↗</span><h3>${title}</h3><p>${text}</p></div>`;}
function previewHTML(){if(!preview.length)return '';return `<div class="import-preview"><h3>辨識預覽 · ${preview.filter(x=>x.record).length} 筆</h3><p class="quiet">尚未儲存。可修改辨識值；錯誤列請修正原文後重新辨識。</p>${preview.map((p,i)=>p.error?`<div class="error">第 ${p.line} 行：${esc(p.source)}<br>${esc(p.error)}</div>`:`<div class="preview-row"><span>第 ${p.line} 行</span><label>日期<input type="date" data-preview="${i}" data-field="date" value="${p.record.date}"></label><label>公尺<input type="number" inputmode="decimal" step="any" data-preview="${i}" data-field="distance" value="${p.record.distance}"></label><label>秒數<input type="number" inputmode="decimal" step="any" data-preview="${i}" data-field="seconds" value="${p.record.seconds}"></label></div>`).join('')}<button class="primary full" id="confirm-import" ${preview.some(x=>x.error)?'disabled':''}>確認匯入 ${preview.filter(x=>x.record).length} 筆紀錄</button></div>`;}
function recordPage(){let list=chronological(own().filter(r=>filter==='all'||r.distance===Number(filter))).reverse();return `<div class="section-head list-heading"><h2>全部紀錄 <span class="count">${list.length}</span></h2><label>距離 <select id="record-filter">${options([['all','全部距離'],...[...new Set(own().map(r=>r.distance))].sort((a,b)=>a-b).map(d=>[String(d),`${d} 公尺`])],filter)}</select></label></div>${!list.length?`<section class="card">${empty('還沒有跑步紀錄','從今天的第一筆開始吧。')}<button class="primary full" data-page="home">＋ 記錄成績</button></section>`:`<div class="record-list">${list.map(r=>{const s=summary(records,r.distance,r.childId),idx=s.list.findIndex(x=>x.id===r.id),previous=s.list[idx-1];return `<article class="card record"><div class="record-date">${short(r.date)}<small>${r.date.slice(0,4)}</small></div><div class="record-main"><div class="record-title"><strong>${r.distance}<small> m</small></strong><b>${f(r.seconds)}<small> 秒</small></b>${r.seconds===s.best.seconds?'<span class="pb">🏆 PB</span>':''}</div><p class="muted">${f(speed(r).ms)} m/s · ${f(speed(r).kmh)} km/h</p>${previous?`<p class="comparison ${r.seconds>previous.seconds?'slower':''}">比前一次${delta(previous.seconds,r.seconds)}</p>`:'<p class="quiet">這個距離的第一筆紀錄</p>'}${r.note?`<p class="record-note">${esc(r.note)}</p>`:''}<div class="tags">${[({standing:'靜止起跑',flying:'助跑',free:'自由跑'})[r.startType],({indoor:'室內',track:'操場',asphalt:'柏油',grass:'草地'})[r.surface],({manual:'手動',video:'影片',electronic:'電子計時'})[r.timingMethod]].filter(Boolean).map(t=>`<span>${t}</span>`).join('')}</div><div class="record-actions"><button data-edit="${esc(r.id)}">編輯／備註</button><button data-copy="${esc(r.id)}">複製</button><button class="danger" data-delete="${esc(r.id)}">刪除</button></div></div></article>`;}).join('')}</div>`}`;}
function chart(s){if(s.list.length<2)return empty('再跑一次，就有趨勢','至少需要兩筆相同距離的成績。');const list=s.list,values=list.map(r=>r.seconds),min=Math.min(...values),max=Math.max(...values),pad=Math.max((max-min)*.15,.1),low=Math.max(0,min-pad),high=max+pad,reverse=settings.find(s=>s.id==='reverse')?.value!==false;const times=list.map(r=>Date.parse(r.date+'T12:00:00Z')),tmin=Math.min(...times),tmax=Math.max(...times);const x=i=>50+(tmax===tmin?i/(list.length-1):(times[i]-tmin)/(tmax-tmin))*550,y=v=>30+(reverse?(v-low)/(high-low):(high-v)/(high-low))*210;const points=list.map((r,i)=>`${x(i)},${y(r.seconds)}`).join(' ');return `<div class="chart-wrap"><svg viewBox="0 0 640 300" role="img" aria-label="${distance} 公尺秒數趨勢圖，${reverse?'秒數越低位置越高':'秒數越低位置越低'}">${Array.from({length:5},(_,i)=>{let v=low+(high-low)*i/4;return `<line x1="50" x2="610" y1="${y(v)}" y2="${y(v)}" stroke="#e6eae9" stroke-dasharray="4 4"/><text x="40" y="${y(v)+4}" text-anchor="end">${v.toFixed(2)}</text>`;}).join('')}<polyline points="${points}" fill="none" stroke="#188870" stroke-width="3" stroke-linejoin="round"/>${list.map((r,i)=>`<circle cx="${x(i)}" cy="${y(r.seconds)}" r="5" fill="#188870" stroke="white" stroke-width="2"><title>${r.date}：${r.seconds} 秒</title></circle>${i===0||i===list.length-1||(list.length<=6)?`<text x="${x(i)}" y="270" text-anchor="middle">${short(r.date)}</text>`:''}`).join('')}</svg></div><details><summary>查看圖表數據</summary><table><thead><tr><th>日期</th><th>秒數</th><th>速度 m/s</th></tr></thead><tbody>${list.map(r=>`<tr><td>${r.date}</td><td>${r.seconds}</td><td>${f(speed(r).ms)}</td></tr>`).join('')}</tbody></table></details>`;}
function analysis(){const s=stat();return `<section class="card"><div class="section-head"><h2>成績趨勢</h2>${distanceSelect()}</div><p class="muted">只比較相同距離 · 秒數越低越好</p><label class="checkbox"><input id="reverse" type="checkbox" ${settings.find(s=>s.id==='reverse')?.value!==false?'checked':''}>反轉 Y 軸，讓進步向上</label>${s?chart(s):empty('讓進步慢慢連成一條線','先新增一筆這個距離的成績。')}</section>${s?`<section class="card analysis-summary"><h2>${distance} 公尺 · 進步摘要</h2>${summaryHTML(s)}</section>`:''}<section class="card"><h2>個人最佳紀錄</h2>${own().length?`<div class="pb-grid">${[...new Set(own().map(r=>r.distance))].sort((a,b)=>a-b).map(d=>{const b=summary(records,d,active().id).best;return `<div><span>${d} 公尺</span><strong>${f(b.seconds)}<small> 秒</small></strong><span>${b.date}</span></div>`;}).join('')}</div>`:'<p class="muted">第一筆成績會成為你的起始紀錄。</p>'}<p class="quiet">手動計時、場地與起跑方式都可能影響成績，建議在相近條件下觀察趨勢。</p></section>`;}
function settingPage(){return `<section class="card"><h2>小跑者</h2><form id="child-form"><label>顯示名稱<input id="child-name" value="${esc(active().name)}" maxlength="30" required></label><button class="secondary" type="submit">儲存名稱</button></form><p class="quiet">第一版使用一位小孩，資料已保留 childId 供未來擴充。</p></section><section class="card"><h2>備份與資料</h2><div class="notice">資料只儲存在目前瀏覽器，不會自動同步。清除網站資料或更換手機前，請先匯出 JSON 備份。</div><div class="settings-row"><div><strong>JSON 完整備份</strong><p>保留全部紀錄、小孩與偏好設定</p></div><button class="secondary" id="export-json">匯出 JSON</button></div><div class="settings-row"><div><strong>CSV 成績表</strong><p>供 Excel、Google Sheets 或分析使用</p></div><button class="secondary" id="export-csv">匯出 CSV</button></div><div class="settings-row"><div><strong>還原 JSON 備份</strong><p>先檢查內容，再確認取代本機資料</p></div><label class="secondary file-label">選擇檔案<input id="import-json" type="file" accept=".json,application/json"></label></div><div id="backup-preview"></div><p class="quiet">目前共 ${records.length} 筆紀錄。${settings.find(s=>s.id==='lastBackup')?`上次匯出：${esc(new Date(settings.find(s=>s.id==='lastBackup').value).toLocaleString('zh-TW'))}`:'尚未匯出備份。'}</p></section><section class="card"><h2>關於小步快跑</h2><p class="muted">無帳號、無追蹤、無 AI API。文字辨識與計算都在你的裝置完成。</p><p class="quiet">首次開啟需要網路；載入完成後會準備離線快取。請確認離線重開可用後再出門。新增時保留原始秒數，畫面顯示四捨五入至小數點後兩位。</p></section>`;}
function capture(){for(const k of ['date','distance','seconds','note','startType','surface','timingMethod'])if($('#'+k))draft[k]=$('#'+k).value;}
function changePage(p){if(page==='home')capture();page=p;history.replaceState(null,'','#'+p);render();window.scrollTo(0,0);}
async function refresh(){[records,children,settings]=await Promise.all([all('records'),all('children'),all('settings')]);}
async function safe(fn){if(busy)return;busy=true;try{await fn();}catch(e){toast(`未完成：${e.message}。資料未成功儲存時請勿關閉頁面。`);}finally{busy=false;}}
function makeRecord(r,index=0){const time=new Date(Date.now()+index).toISOString();return {...r,id:crypto.randomUUID(),childId:active().id,createdAt:time,updatedAt:time};}
async function saveRecords(incoming){const candidate=[...records];for(const r of incoming){validate(r);const notes=warnings(r,candidate);if(notes.length&&!confirm(notes.join('\n')+'\n\n確認保留原數值並繼續？'))return false;candidate.push(r);}await write(incoming.map(value=>({store:'records',value})));await refresh();return true;}
async function setSetting(id,value){await write([{store:'settings',value:{id,value}}]);settings=await all('settings');}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>changePage(b.dataset.page));$('.brand').onclick=e=>{e.preventDefault();changePage('home');};
 if($('#run-form')){$('#run-form').oninput=capture;$('#custom').onclick=()=>{$('#distance').focus();$('#distance').select();};document.querySelectorAll('[data-distance]').forEach(b=>b.onclick=()=>{capture();draft.distance=Number(b.dataset.distance);distance=draft.distance;render();$('#seconds').focus();});$('#cancel-edit')?.addEventListener('click',()=>{editing=null;draft={...draft,date:today(),seconds:'',note:'',startType:'',surface:'',timingMethod:''};render();});$('#run-form').onsubmit=e=>{e.preventDefault();safe(async()=>{capture();const r=validate({...draft,distance:Number(draft.distance),seconds:Number(draft.seconds)});const previousBest=summary(records,r.distance,active().id)?.best;let message;
 if(editing){const old=records.find(x=>x.id===editing);const updated={...old,...r,updatedAt:new Date().toISOString()};const notes=warnings(updated,records);if(notes.length&&!confirm(notes.join('\n')+'\n確認儲存修改？'))return;await write([{store:'records',value:updated}]);await refresh();message='紀錄已更新';}
 else{if(!await saveRecords([makeRecord(r)]))return;message=previousBest&&r.seconds<previousBest.seconds?`🏆 新個人最佳！${r.distance} 公尺 ${f(r.seconds)} 秒，比原紀錄 ${f(previousBest.seconds)} 秒快 ${f(previousBest.seconds-r.seconds)} 秒`:`已新增 ${r.distance} 公尺 · ${f(r.seconds)} 秒${!previousBest?'，第一筆 PB！':''}`;}
 editing=null;distance=r.distance;draft={...draft,date:today(),distance:r.distance,seconds:'',note:'',startType:'',surface:'',timingMethod:''};await setSetting('distance',r.distance);render();toast(message);$('#seconds').focus();});};$('#parse').onclick=()=>{preview=parseText($('#paste').value);$('#preview').innerHTML=previewHTML();bindPreview();if(!preview.length)toast('請先貼上跑步紀錄');};bindPreview();}
 $('#analysis-distance')?.addEventListener('change',e=>{if(page==='home')capture();distance=Number(e.target.value);render();});$('#record-filter')?.addEventListener('change',e=>{filter=e.target.value;render();});$('#reverse')?.addEventListener('change',e=>safe(async()=>{await setSetting('reverse',e.target.checked);render();}));
 document.querySelectorAll('[data-edit],[data-copy]').forEach(b=>b.onclick=()=>{const r=records.find(x=>x.id===(b.dataset.edit||b.dataset.copy));editing=b.dataset.edit?r.id:null;draft={...r,date:b.dataset.copy?today():r.date};page='home';render();window.scrollTo(0,0);$('#seconds').focus();if(b.dataset.copy)toast('已複製到輸入欄，確認後再新增');});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>safe(async()=>{const r=records.find(x=>x.id===b.dataset.delete);if(!confirm(`刪除 ${r.date} · ${r.distance} 公尺 ${r.seconds} 秒？\n刪除後無法復原，除非已有 JSON 備份。`))return;await write([{store:'records',delete:r.id}]);await refresh();render();toast('已刪除這筆紀錄；可由既有 JSON 備份還原。');}));
 $('#child-form')?.addEventListener('submit',e=>{e.preventDefault();safe(async()=>{const name=$('#child-name').value.trim();if(!name)throw Error('名稱不可空白');await write([{store:'children',value:{...active(),name}}]);await refresh();render();toast('名稱已更新');});});$('#export-json')?.addEventListener('click',()=>safe(async()=>{download(`run-data-${today()}.json`,JSON.stringify({version:1,exportedAt:new Date().toISOString(),children,records,settings},null,2),'application/json');await setSetting('lastBackup',new Date().toISOString());render();toast('已產生 JSON 備份，請確認檔案已下載保存');}));$('#export-csv')?.addEventListener('click',()=>download(`run-data-${today()}.csv`,csv(own()),'text/csv;charset=utf-8'));
 $('#import-json')?.addEventListener('change',e=>safe(async()=>{backup=null;$('#backup-preview').innerHTML='';const file=e.target.files[0];if(!file)return;if(file.size>10*1024*1024)throw Error('備份檔請小於 10 MB');backup=validateBackup(JSON.parse(await file.text()));$('#backup-preview').innerHTML=`<div class="notice"><strong>有效備份：${backup.records.length} 筆紀錄、${backup.children.length} 位小孩</strong><p>將取代目前 ${records.length} 筆紀錄。建議先匯出目前資料。</p><button id="restore" class="primary">確認取代並還原</button></div>`;$('#restore').onclick=()=>safe(async()=>{if(!confirm('確定以備份取代本機全部紀錄、名字與設定？\n未備份的現有資料將無法復原。'))return;const b=backup;if(!b.children.length)throw Error('備份至少需有一位小孩');const safeSettings=(Array.isArray(b.settings)?b.settings:[]).filter(s=>(s.id==='distance'&&typeof s.value==='number'&&s.value>0&&Number.isFinite(s.value))||(s.id==='reverse'&&typeof s.value==='boolean'));await write([...['records','children','settings'].map(store=>({store,clear:true})),...b.records.map(value=>({store:'records',value})),...b.children.map(value=>({store:'children',value})),...safeSettings.map(value=>({store:'settings',value}))]);await refresh();distance=settings.find(s=>s.id==='distance')?.value||30;draft={date:today(),distance,seconds:'',note:'',startType:'',surface:'',timingMethod:''};editing=null;preview=[];backup=null;render();toast('備份已還原，原本機資料已被取代。');});}));
}
function bindPreview(){if($('#paste')){$('#paste').value=pasteDraft;$('#paste').oninput=e=>{pasteDraft=e.target.value;preview=[];$('#preview').innerHTML='';};}document.querySelectorAll('[data-preview]').forEach(input=>input.oninput=()=>{preview[Number(input.dataset.preview)].record[input.dataset.field]=input.dataset.field==='date'?input.value:Number(input.value);});$('#confirm-import')?.addEventListener('click',()=>safe(async()=>{if(preview.some(x=>x.error)||!preview.length)return;const incoming=preview.map((p,i)=>makeRecord(validate(p.record),i));if(!await saveRecords(incoming))return;preview=[];pasteDraft='';capture();render();toast(`已匯入 ${incoming.length} 筆紀錄`);}));}
try{await openDB();await refresh();if(!children.length){await write([{store:'children',value:{id:'child_01',name:'小孩',birthday:null}}]);await refresh();}distance=settings.find(s=>s.id==='distance')?.value||30;draft.distance=distance;const route=location.hash.slice(1);if(['home','records','analysis','settings'].includes(route))page=route;render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>toast('離線快取未啟用；請保持網路連線。'));}catch(e){$('#app').innerHTML=`<main class="card"><h1>無法開啟本機儲存空間</h1><p>${esc(e.message)}</p><p>請允許瀏覽器使用網站儲存空間，或改用一般瀏覽模式後重新整理。尚未寫入任何新紀錄。</p><button onclick="location.reload()">重新整理</button></main>`;}
